### ISSUE TITLE
importing functions fails

### ISSUE THREAD

**Issue by domeckert** [aragagnin/hydro_mc#1]
Hello,

When I try to import functions from the hydro_mc package it fails, even though hydro_mc seem to be imported correctly.

<img width="790" alt="image" src="https://github.com/aragagnin/hydro_mc/assets/47885645/365569db-4043-428e-b019-dcf22fc9e17e">

To solve the issue I created a `__init__.py` with the following content:

`from __future__ import absolute_import`
`from .hydro_mc import *`

that should solve the issue.

**Comment by aragagnin** [comment]
Hi Dominique,

It is a very good idea for people who want to keep `hydro_mc.py` inside its github folder (my ideal usecase was that people would download just one file from the repository)

I created a `__init__.py` as you suggested and now I am also able to import `hydro_mc`  from a parent folder.

Thanks

**Comment by domeckert** [comment]
Thanks @aragagnin . Indeed in this way I am able to add hydro_mc to the site packages and import from anywhere, which is much more convenient.

Cheers
Dominique
